# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - release-*

pr:
  branches:
    include:
    - main
    exclude:
    - doc/*
    - README.rst

pool:
  vmImage: ubuntu-latest

variables:
  triggeredByPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]

steps:

- script: echo 'Dont show this for PRs'
  condition: and(succeeded(), eq(variables.triggeredByPullRequest, false))

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Use Python 3.10'

- bash: |
    export PACKAGE_VERSION="$(python setup.py --version)"
    echo "Package Version: ${PACKAGE_VERSION}"
    echo "##vso[task.setvariable variable=packageVersionFormatted;]release-${PACKAGE_VERSION}"
  displayName: 'Get package version'

- script: echo 'version $(packageVersionFormatted)'
  displayName: 'test'

- script: |
    echo "building package"
    echo "publishing"
  displayName: 'only build on tag'
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], variables['packageVersionFormatted']))


